; Opt-in: "open Atp_limitations.Limitations" or dune-depend on atp_limitations.
(library
 (name atp_limitations)
 (libraries atp num str)
 (flags
  (:standard
   -w
   +a-4-27-32..70+32+33+39+41+52+56
   -warn-error
   -a
   -no-strict-sequence
   -open Format
   -open Num
   -open Str))
 (inline_tests)
 (preprocess
  (pps ppx_atp_quot ppx_inline_test ppx_expect)))
